os: osx
language: objective-c
osx_image: xcode10.1
sudo: false
env:
  global:
  - THEOS=~/theos
  - SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk
before_install:
- brew install dpkg ldid
- git clone --recursive git://github.com/theos/theos.git ~/theos
script:
- make clean package
before_deploy:
- git config --local user.name "Xyon"
- git config --local user.email "xyon88@github.com"
- export RELEASE_PKG_FILE=$(ls ./packages/*.deb)
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: UQ3OZ+fEyrlXRFr7FVMCat9kkplDZOlaQMhpzfdJvNC31d66iHlO5rSTsqjqmwiU7WIjsEMCGoM9+jhoGld5kIQIaA4pJrADidTzaNq/zdyelZUZvXOd/UDU0l18luQ6AlyUcV1n6vGRCqGALUmTlL5XxX8dC4VgGCWww9dx0192wlwfJFSG6PrJEBrnE7g8HfFIaDKd/et8Lpv4TC7yt8vnWMwYi6CrnYVWmmwwiolMiWhGtUju2fxWICrXUiKrjAkrXiQpbipFNQcnBKJ/eDoV+YLwTlh8uJUOw89e5FF5S7g5of1/wLwgtOWfHxXZ8MhlxRK8mA8disvgjJf18AEQF0zwHiJ2wEWtjC8hBfyZth9HQ8Qg3SopOwq3z2OAwLuYA0h0hRSYNkGYZMnBO6I+SaqC8TGwv/y/aTPiCVbdDbOHnSX9ZQRrTKin1I6FFfNCJtKbQd/TXWC6P93wnQfDedhZEuI+1J1rcxBv6j0DIsz0qNMFCZ01moPWQSPURfB5NDZmK/hFlWN/KadBunzMDJefo1IPPEqAxl4sGvs+E6397vXAmGRRSc8D7R59Oaw6a+fEslazXIRkDzpeBPNY+c4qlSBIeCiIvnm5WjS41vB/9M85g4ppdKDgnd3VA429DlsqzzbYaOccGnaZehVTq1bU3JTh86a09l4J1qU=
  file_glob: true
  file: '${RELEASE_PKG_FILE}'
  on:
    repo: Xyon88/PandoraPlus
    branch: master
